# Schemas
schemas:
  # Общие схемы для подходов
  TrainingSet:
    type: object
    required:
      - setId
      - exerciseId
      - setNumber
    properties:
      setId:
        type: string
        format: uuid
        example: "5922f4f1-7989-4e02-80b0-77ecee62a25b"
      exerciseId:
        type: string
        format: uuid
        example: "10"
      setNumber:
        type: integer
        minimum: 1
        maximum: 20
        example: 1
      weight:
        type: number
        minimum: 0
        maximum: 1000
        example: 103
      reps:
        type: integer
        minimum: 1
        maximum: 100
        example: 10
      restTime:
        type: integer
        minimum: 0
        maximum: 600
        description: "Время отдыха в секундах"
        example: 60
      completed:
        type: boolean
        default: false
      completedAt:
        type: string
        format: date-time
      notes:
        type: string
        maxLength: 500
        example: ""

  # Общая схема упражнения (для активной тренировки)
  ActiveExercise:
    type: object
    required:
      - id
      - exerciseId
      - name
      - muscleGroups
      - type
      - useCustomSets
      - sets
    properties:
      id:
        type: string
        format: uuid
        example: "b1ae9b23-3aeb-45de-b828-185ff1cc9240"
      exerciseId:
        type: string
        format: uuid
        example: "7"
      name:
        type: string
        example: "Скручивания на пресс"
      muscleGroups:
        type: array
        items:
          type: string
        example: ["strength", "abs"]
      type:
        type: string
        enum:
          - strength
          - cardio
          - flexibility
          - balance
          - yoga
          - pilates
        example: "strength"
      useCustomSets:
        type: boolean
        default: false
        example: false
      sets:
        type: array
        items:
          $ref: "#/schemas/TrainingSet"
      notes:
        type: string
        maxLength: 1000
        example: "Упражнение на пресс"

  # Основная схема активной тренировки
  ActiveTraining:
    type: object
    required:
      - id
      - name
      - exercises
    properties:
      id:
        type: string
        format: uuid
      name:
        type: string
        example: "Силовая тренировка на грудь"
      description:
        type: string
        example: "Тренировка для развития грудных мышц"
      exercises:
        type: array
        items:
          $ref: "#/schemas/ActiveExercise"
      time:
        type: number
        minimum: 0
        maximum: 1440
        description: "Время выполнения в минутах"
        example: 45
      status:
        type: string
        enum:
          - draft
          - in_progress
          - completed
          - cancelled
        default: "draft"
      startedAt:
        type: string
        format: date-time
      completedAt:
        type: string
        format: date-time
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time

  # Для создания новой активной тренировки
  CreateActiveTraining:
    type: object
    required:
      - name
      - exercises
    properties:
      name:
        type: string
      description:
        type: string
      exercises:
        type: array
        items:
          $ref: "#/schemas/ActiveExercise"
      status:
        type: string
        enum:
          - draft
          - in_progress
          - completed
          - cancelled
        default: "draft"

  # Для обновления активной тренировки
  UpdateActiveTraining:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      exercises:
        type: array
        items:
          $ref: "#/schemas/ActiveExercise"
      time:
        type: number
        minimum: 0
      status:
        type: string
        enum:
          - draft
          - in_progress
          - completed
          - cancelled

  # Для ответа со списком активных тренировок
  ActiveTrainingsList:
    type: object
    required:
      - list
      - total
      - totalPages
    properties:
      list:
        type: array
        items:
          $ref: "#/schemas/ActiveTraining"
      total:
        type: integer
      totalPages:
        type: integer

  # Для старта тренировки (из training-start.yaml)
  StartTrainingRequest:
    type: object
    required:
      - trainingId
    properties:
      trainingId:
        type: string
        format: uuid
      time:
        type: number
        minimum: 0
        description: "Планируемое время в минутах"

  # Для завершения тренировки
  CompleteTrainingRequest:
    type: object
    required:
      - time
    properties:
      time:
        type: number
        minimum: 0
        description: "Фактическое время выполнения в минутах"
      notes:
        type: string

  # История тренировок (завершенные)
  TrainingHistory:
    type: object
    required:
      - id
      - name
      - time
      - status
      - completedAt
    properties:
      id:
        type: string
        format: uuid
      name:
        type: string
      description:
        type: string
      exercises:
        type: array
        items:
          $ref: "#/schemas/ActiveExercise"
      time:
        type: number
        description: "Время выполнения в минутах"
      status:
        type: string
        enum:
          - completed
          - cancelled
      startedAt:
        type: string
        format: date-time
      completedAt:
        type: string
        format: date-time
      notes:
        type: string

# Endpoints

## Базовые CRUD операции для активных тренировок
getActiveTrainings:
  summary: Get all active trainings
  security:
    - bearerAuth: []
  parameters:
    - name: page
      in: query
      required: false
      schema:
        type: integer
        default: 1
    - name: limit
      in: query
      required: false
      schema:
        type: integer
        default: 10
    - name: status
      in: query
      required: false
      schema:
        type: string
        enum:
          - draft
          - in_progress
          - completed
          - cancelled
    - name: search
      in: query
      required: false
      schema:
        type: string
  responses:
    "200":
      description: List of active trainings
      content:
        application/json:
          schema:
            $ref: "#/schemas/ActiveTrainingsList"
    "401":
      description: Unauthorized

createActiveTraining:
  summary: Create a new active training
  security:
    - bearerAuth: []
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "#/schemas/CreateActiveTraining"
  responses:
    "201":
      description: Active training created successfully
      content:
        application/json:
          schema:
            $ref: "#/schemas/ActiveTraining"
    "400":
      description: Invalid input
    "401":
      description: Unauthorized

getActiveTrainingById:
  summary: Get active training by id
  security:
    - bearerAuth: []
  parameters:
    - name: trainingId
      in: path
      required: true
      schema:
        type: string
        format: uuid
  responses:
    "200":
      description: Active training
      content:
        application/json:
          schema:
            $ref: "#/schemas/ActiveTraining"
    "401":
      description: Unauthorized
    "404":
      description: Active training not found

updateActiveTraining:
  summary: Update an active training
  security:
    - bearerAuth: []
  parameters:
    - name: trainingId
      in: path
      required: true
      schema:
        type: string
        format: uuid
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "#/schemas/UpdateActiveTraining"
  responses:
    "200":
      description: Active training updated successfully
      content:
        application/json:
          schema:
            $ref: "#/schemas/ActiveTraining"
    "400":
      description: Invalid input
    "401":
      description: Unauthorized
    "404":
      description: Active training not found

deleteActiveTraining:
  summary: Delete an active training
  security:
    - bearerAuth: []
  parameters:
    - name: trainingId
      in: path
      required: true
      schema:
        type: string
        format: uuid
  responses:
    "204":
      description: Active training deleted successfully
    "401":
      description: Unauthorized
    "404":
      description: Active training not found

## Операции с тренировочным процессом
startActiveTraining:
  summary: Start an active training session
  security:
    - bearerAuth: []
  parameters:
    - name: trainingId
      in: path
      required: true
      schema:
        type: string
        format: uuid
  requestBody:
    required: false
    content:
      application/json:
        schema:
          $ref: "#/schemas/StartTrainingRequest"
  responses:
    "200":
      description: Training started successfully
      content:
        application/json:
          schema:
            $ref: "#/schemas/ActiveTraining"
    "400":
      description: Invalid input
    "401":
      description: Unauthorized
    "404":
      description: Training not found
    "409":
      description: Training already started

pauseActiveTraining:
  summary: Pause an active training
  security:
    - bearerAuth: []
  parameters:
    - name: trainingId
      in: path
      required: true
      schema:
        type: string
        format: uuid
  responses:
    "200":
      description: Training paused successfully
      content:
        application/json:
          schema:
            $ref: "#/schemas/ActiveTraining"
    "401":
      description: Unauthorized
    "404":
      description: Training not found

resumeActiveTraining:
  summary: Resume a paused training
  security:
    - bearerAuth: []
  parameters:
    - name: trainingId
      in: path
      required: true
      schema:
        type: string
        format: uuid
  responses:
    "200":
      description: Training resumed successfully
      content:
        application/json:
          schema:
            $ref: "#/schemas/ActiveTraining"
    "401":
      description: Unauthorized
    "404":
      description: Training not found

completeActiveTraining:
  summary: Complete an active training
  security:
    - bearerAuth: []
  parameters:
    - name: trainingId
      in: path
      required: true
      schema:
        type: string
        format: uuid
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "#/schemas/CompleteTrainingRequest"
  responses:
    "200":
      description: Training completed successfully
      content:
        application/json:
          schema:
            $ref: "#/schemas/TrainingHistory"
    "400":
      description: Invalid input
    "401":
      description: Unauthorized
    "404":
      description: Training not found

cancelActiveTraining:
  summary: Cancel an active training
  security:
    - bearerAuth: []
  parameters:
    - name: trainingId
      in: path
      required: true
      schema:
        type: string
        format: uuid
  responses:
    "200":
      description: Training cancelled successfully
      content:
        application/json:
          schema:
            $ref: "#/schemas/ActiveTraining"
    "401":
      description: Unauthorized
    "404":
      description: Training not found

## Управление упражнениями в активной тренировке
addExerciseToActiveTraining:
  summary: Add exercise to active training
  security:
    - bearerAuth: []
  parameters:
    - name: trainingId
      in: path
      required: true
      schema:
        type: string
        format: uuid
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          required:
            - exerciseId
            - name
          properties:
            exerciseId:
              type: string
              format: uuid
            name:
              type: string
            muscleGroups:
              type: array
              items:
                type: string
            type:
              type: string
            sets:
              type: array
              items:
                $ref: "#/schemas/TrainingSet"
              default: []
            notes:
              type: string
  responses:
    "200":
      description: Exercise added successfully
      content:
        application/json:
          schema:
            $ref: "#/schemas/ActiveTraining"
    "400":
      description: Invalid input
    "401":
      description: Unauthorized
    "404":
      description: Training not found

removeExerciseFromActiveTraining:
  summary: Remove exercise from active training
  security:
    - bearerAuth: []
  parameters:
    - name: trainingId
      in: path
      required: true
      schema:
        type: string
        format: uuid
    - name: exerciseId
      in: path
      required: true
      schema:
        type: string
        format: uuid
  responses:
    "200":
      description: Exercise removed successfully
      content:
        application/json:
          schema:
            $ref: "#/schemas/ActiveTraining"
    "401":
      description: Unauthorized
    "404":
      description: Training or exercise not found

updateExerciseInActiveTraining:
  summary: Update exercise in active training
  security:
    - bearerAuth: []
  parameters:
    - name: trainingId
      in: path
      required: true
      schema:
        type: string
        format: uuid
    - name: exerciseId
      in: path
      required: true
      schema:
        type: string
        format: uuid
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            name:
              type: string
            muscleGroups:
              type: array
              items:
                type: string
            type:
              type: string
            useCustomSets:
              type: boolean
            sets:
              type: array
              items:
                $ref: "#/schemas/TrainingSet"
            notes:
              type: string
  responses:
    "200":
      description: Exercise updated successfully
      content:
        application/json:
          schema:
            $ref: "#/schemas/ActiveTraining"
    "400":
      description: Invalid input
    "401":
      description: Unauthorized
    "404":
      description: Training or exercise not found

## История тренировок
getTrainingHistory:
  summary: Get training history
  security:
    - bearerAuth: []
  parameters:
    - name: page
      in: query
      required: false
      schema:
        type: integer
        default: 1
    - name: limit
      in: query
      required: false
      schema:
        type: integer
        default: 10
    - name: startDate
      in: query
      required: false
      schema:
        type: string
        format: date
    - name: endDate
      in: query
      required: false
      schema:
        type: string
        format: date
  responses:
    "200":
      description: List of training history
      content:
        application/json:
          schema:
            type: object
            required:
              - list
              - total
              - totalPages
            properties:
              list:
                type: array
                items:
                  $ref: "#/schemas/TrainingHistory"
              total:
                type: integer
              totalPages:
                type: integer
    "401":
      description: Unauthorized
