/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login user */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["LoginRequest"];
        };
      };
      responses: {
        /** @description Login successful */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AuthResponse"];
          };
        };
        401: components["responses"]["UnauthorizedError"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register new user */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["RegisterRequest"];
        };
      };
      responses: {
        /** @description Registration successful */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AuthResponse"];
          };
        };
        400: components["responses"]["BadRequestError"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh access token */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: {
          refreshToken?: string;
        };
      };
      requestBody?: never;
      responses: {
        /** @description Access token refreshed successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AuthResponse"];
          };
        };
        401: components["responses"]["UnauthorizedError"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/exercises": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all exercises */
    get: {
      parameters: {
        query?: {
          page?: number;
          limit?: number;
          favorite?: boolean;
          search?: string;
          muscleGroup?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of exercises */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ExercisesList"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /** Create a new exercise */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateExercise"];
        };
      };
      responses: {
        /** @description Exercise created successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Exercise"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/exercises/{exerciseId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get an exercise by id */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          exerciseId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Exercise */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Exercise"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Exercise not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    /** Update an exercise */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          exerciseId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateExercise"];
        };
      };
      responses: {
        /** @description Exercise updated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Exercise"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Exercise not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    /** Delete an exercise */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          exerciseId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Exercise deleted successfully */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Exercise not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/trainings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all trainings */
    get: {
      parameters: {
        query?: {
          page?: number;
          limit?: number;
          type?:
            | "cardio"
            | "strength"
            | "flexibility"
            | "balance"
            | "yoga"
            | "pilates";
          search?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of trainings */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["TrainingsList"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /** Create a new training */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateTraining"];
        };
      };
      responses: {
        /** @description Training created successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Training"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/trainings/{trainingId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a training by id */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          trainingId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Training */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Training"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Training not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    /** Update a training */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          trainingId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateTraining"];
        };
      };
      responses: {
        /** @description Training updated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Training"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Training not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    /** Delete a training */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          trainingId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Training deleted successfully */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Training not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/active-trainings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all active trainings */
    get: {
      parameters: {
        query?: {
          page?: number;
          limit?: number;
          status?: "draft" | "in_progress" | "completed" | "cancelled";
          search?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of active trainings */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ActiveTrainingsList"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /** Create a new active training */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateActiveTraining"];
        };
      };
      responses: {
        /** @description Active training created successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ActiveTraining"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/active-trainings/{trainingId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get active training by id */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          trainingId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Active training */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ActiveTraining"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Active training not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    /** Update an active training */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          trainingId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateActiveTraining"];
        };
      };
      responses: {
        /** @description Active training updated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ActiveTraining"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Active training not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    /** Delete an active training */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          trainingId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Active training deleted successfully */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Active training not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/active-trainings/{trainingId}/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start an active training session */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          trainingId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["StartTrainingRequest"];
        };
      };
      responses: {
        /** @description Training started successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ActiveTraining"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Training not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Training already started */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/active-trainings/{trainingId}/pause": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Pause an active training */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          trainingId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Training paused successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ActiveTraining"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Training not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/active-trainings/{trainingId}/resume": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Resume a paused training */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          trainingId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Training resumed successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ActiveTraining"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Training not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/active-trainings/{trainingId}/complete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Complete an active training */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          trainingId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CompleteTrainingRequest"];
        };
      };
      responses: {
        /** @description Training completed successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["TrainingHistory"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Training not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/active-trainings/{trainingId}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cancel an active training */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          trainingId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Training cancelled successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ActiveTraining"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Training not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/active-trainings/{trainingId}/exercises": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add exercise to active training */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          trainingId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** Format: uuid */
            exerciseId: string;
            name: string;
            muscleGroups?: string[];
            type?: string;
            /** @default [] */
            sets?: components["schemas"]["TrainingSet"][];
            notes?: string;
          };
        };
      };
      responses: {
        /** @description Exercise added successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ActiveTraining"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Training not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/active-trainings/{trainingId}/exercises/{exerciseId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update exercise in active training */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          trainingId: string;
          exerciseId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            name?: string;
            muscleGroups?: string[];
            type?: string;
            useCustomSets?: boolean;
            sets?: components["schemas"]["TrainingSet"][];
            notes?: string;
          };
        };
      };
      responses: {
        /** @description Exercise updated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ActiveTraining"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Training or exercise not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    /** Remove exercise from active training */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          trainingId: string;
          exerciseId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Exercise removed successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ActiveTraining"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Training or exercise not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/training-history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get training history */
    get: {
      parameters: {
        query?: {
          page?: number;
          limit?: number;
          startDate?: string;
          endDate?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of training history */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              list: components["schemas"]["TrainingHistory"][];
              total: number;
              totalPages: number;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    LoginRequest: {
      /** Format: email */
      email: string;
      /** Format: password */
      password: string;
    };
    User: {
      id: string;
      /** Format: email */
      email: string;
    };
    AuthResponse: {
      accessToken: string;
      user: components["schemas"]["User"];
    };
    Error: {
      message: string;
      code: string;
    };
    RegisterRequest: {
      /** Format: email */
      email: string;
      /** Format: password */
      password: string;
    };
    Exercise: {
      id: string;
      name: string;
      favorite: boolean;
      muscleGroups: string[];
      description?: string;
      videoUrl: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    ExercisesList: {
      list: components["schemas"]["Exercise"][];
      total: number;
      totalPages: number;
    };
    CreateExercise: {
      name: string;
      /** @default false */
      favorite: boolean;
      muscleGroups: string[];
      description?: string;
      videoUrl: string;
    };
    UpdateExercise: {
      name?: string;
      favorite?: boolean;
      muscleGroups?: string[];
      description?: string;
      videoUrl?: string;
    };
    ExerciseForm: {
      id: string;
      exerciseId: string;
      name: string;
      type: string[];
      notes: string;
    };
    Training: {
      id: string;
      name: string;
      exercises: components["schemas"]["ExerciseForm"][];
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    TrainingsList: {
      list: components["schemas"]["Training"][];
      total: number;
      totalPages: number;
    };
    CreateTraining: {
      name: string;
      exercises: components["schemas"]["ExerciseForm"][];
    };
    UpdateTraining: {
      name?: string;
      exercises?: components["schemas"]["ExerciseForm"][];
    };
    TrainingSet: {
      /**
       * Format: uuid
       * @example 5922f4f1-7989-4e02-80b0-77ecee62a25b
       */
      setId: string;
      /**
       * Format: uuid
       * @example 10
       */
      exerciseId: string;
      /** @example 1 */
      setNumber: number;
      /** @example 103 */
      weight?: number;
      /** @example 10 */
      reps?: number;
      /**
       * @description Время отдыха в секундах
       * @example 60
       */
      restTime?: number;
      /** @default false */
      completed: boolean;
      /** Format: date-time */
      completedAt?: string;
      /** @example  */
      notes?: string;
    };
    ActiveExercise: {
      completedSets: any;
      /**
       * Format: uuid
       * @example b1ae9b23-3aeb-45de-b828-185ff1cc9240
       */
      id: string;
      /**
       * Format: uuid
       * @example 7
       */
      exerciseId: string;
      /** @example Скручивания на пресс */
      name: string;
      /** @example [
       *       "strength",
       *       "abs"
       *     ] */
      muscleGroups: string[];
      /**
       * @example strength
       * @enum {string}
       */
      type:
        | "strength"
        | "cardio"
        | "flexibility"
        | "balance"
        | "yoga"
        | "pilates";
      /**
       * @default false
       * @example false
       */
      useCustomSets: boolean;
      sets: components["schemas"]["TrainingSet"][];
      /** @example Упражнение на пресс */
      notes?: string;
    };
    ActiveTraining: {
      /** Format: uuid */
      id: string;
      /** @example Силовая тренировка на грудь */
      name: string;
      /** @example Тренировка для развития грудных мышц */
      description?: string;
      exercises: components["schemas"]["ActiveExercise"][];
      /**
       * @description Время выполнения в минутах
       * @example 45
       */
      time?: number;
      /**
       * @default draft
       * @enum {string}
       */
      status: "draft" | "in_progress" | "completed" | "cancelled";
      /** Format: date-time */
      startedAt?: string;
      /** Format: date-time */
      completedAt?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    ActiveTrainingsList: {
      list: components["schemas"]["ActiveTraining"][];
      total: number;
      totalPages: number;
    };
    CreateActiveTraining: {
      name: string;
      description?: string;
      exercises: components["schemas"]["ActiveExercise"][];
      /**
       * @default draft
       * @enum {string}
       */
      status: "draft" | "in_progress" | "completed" | "cancelled";
    };
    UpdateActiveTraining: {
      name?: string;
      description?: string;
      exercises?: components["schemas"]["ActiveExercise"][];
      time?: number;
      /** @enum {string} */
      status?: "draft" | "in_progress" | "completed" | "cancelled";
    };
    StartTrainingRequest: {
      /** Format: uuid */
      trainingId: string;
      /** @description Планируемое время в минутах */
      time?: number;
    };
    CompleteTrainingRequest: {
      /** @description Фактическое время выполнения в минутах */
      time: number;
      notes?: string;
    };
    TrainingHistory: {
      /** Format: uuid */
      id: string;
      name: string;
      description?: string;
      exercises?: components["schemas"]["ActiveExercise"][];
      /** @description Время выполнения в минутах */
      time: number;
      /** @enum {string} */
      status: "completed" | "cancelled";
      /** Format: date-time */
      startedAt?: string;
      /** Format: date-time */
      completedAt: string;
      notes?: string;
    };
  };
  responses: {
    /** @description Unauthorized */
    UnauthorizedError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Bad request */
    BadRequestError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
