/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Body */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AuthLoginBody"];
                };
            };
            responses: {
                /** @description 200 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokensPair"];
                    };
                };
                /** @description 401 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "InvalidCredentials";
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Body */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AuthRegisterBody"];
                };
            };
            responses: {
                /** @description 200 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokensPair"];
                    };
                };
                /** @description 400 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "AlreadyExists";
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Body */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AuthRefreshBody"];
                };
            };
            responses: {
                /** @description 200 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokensPair"];
                    };
                };
                /** @description 401 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "Unauthorized";
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profile"];
                    };
                };
                /** @description 401 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "Unauthorized";
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercise-type": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    filter?: string;
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            content: components["schemas"]["ExerciseType"][];
                            meta: {
                                limit: number;
                                page: number;
                                pages: number;
                            };
                        };
                    };
                };
                /** @description 422 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Body */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ExerciseTypeCreateBody"];
                };
            };
            responses: {
                /** @description 200 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExerciseType"];
                    };
                };
                /** @description 422 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Body */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ExerciseTypeUpdateBody"];
                };
            };
            responses: {
                /** @description 200 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExerciseType"];
                    };
                };
                /** @description 422 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/exercise-type/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExerciseType"];
                    };
                };
                /** @description 404 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "NotFound";
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description 404 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "NotFound";
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/training": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    filter?: string;
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            content: components["schemas"]["Training"][];
                            meta: {
                                limit: number;
                                page: number;
                                pages: number;
                            };
                        };
                    };
                };
                /** @description 422 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Body */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TrainingCreateBody"];
                };
            };
            responses: {
                /** @description 200 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Training"];
                    };
                };
                /** @description 422 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Body */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TrainingUpdateBody"];
                };
            };
            responses: {
                /** @description 200 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Training"];
                    };
                };
                /** @description 422 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/training/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Training"];
                    };
                };
                /** @description 404 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "NotFound";
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description 404 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "NotFound";
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/active-training": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActiveTraining"];
                    };
                };
                /** @description 404 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "NotFound";
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/active-training/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Body */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ActiveTrainingStartBody"];
                };
            };
            responses: {
                /** @description 200 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActiveTraining"];
                    };
                };
                /** @description 400 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "AlreadyExists";
                    };
                };
                /** @description 404 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "NotFound";
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/active-training/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Body */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateActiveTrainingBody"];
                };
            };
            responses: {
                /** @description 200 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActiveTraining"];
                    };
                };
                /** @description 404 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "NotFound";
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/active-training/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Body */
            requestBody?: {
                content: {
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description 200 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description 404 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "NotFound";
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/training-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    filter?: string;
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            content: components["schemas"]["TrainingHistory"][];
                            meta: {
                                limit: number;
                                page: number;
                                pages: number;
                            };
                        };
                    };
                };
                /** @description 422 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Body */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TrainingHistoryUpdate"];
                };
            };
            responses: {
                /** @description 200 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrainingHistory"];
                    };
                };
                /** @description 422 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/training-history/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrainingHistory"];
                    };
                };
                /** @description 404 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "NotFound";
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description 404 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "NotFound";
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthLoginBody */
        AuthLoginBody: {
            email: string;
            password: string;
        };
        /** TokensPair */
        TokensPair: {
            accessToken: string;
            refreshToken: string;
        };
        /** AuthRegisterBody */
        AuthRegisterBody: {
            email: string;
            password: string;
        };
        /** AuthRefreshBody */
        AuthRefreshBody: {
            refreshToken: string;
        };
        /** Profile */
        Profile: {
            id: string;
            email: string;
        };
        /** ExerciseTypeCreateBody */
        ExerciseTypeCreateBody: {
            name: string;
            favorite?: boolean;
            description?: string;
            restTime?: number;
            muscleGroups?: string[];
        };
        /** ExerciseType */
        ExerciseType: {
            id: string;
            name: string;
            favorite: boolean;
            description: string;
            restTime: number;
            muscleGroups: string[];
        };
        /** ExerciseTypeUpdateBody */
        ExerciseTypeUpdateBody: {
            id: string;
            name?: string;
            favorite?: boolean;
            description?: string;
            restTime?: number;
            muscleGroups?: string[];
        };
        /** TrainingCreateBody */
        TrainingCreateBody: {
            name: string;
            favorite?: boolean;
            description?: string;
            exerciseTypes: {
                id: string;
            }[];
        };
        /** Training */
        Training: {
            id: string;
            name: string;
            favorite: boolean;
            description: string;
            exerciseTypes: {
                id: string;
                name: string;
                favorite: boolean;
                description: string;
                muscleGroups: string[];
                restTime: number;
            }[];
        };
        /** TrainingUpdateBody */
        TrainingUpdateBody: {
            id: string;
            name?: string;
            favorite?: boolean;
            description?: string;
            exerciseTypes: {
                id: string;
            }[];
        };
        /** ActiveTraining */
        ActiveTraining: {
            dateStart: string;
            name: string;
            description: string;
            exercises: {
                id: string;
                name: string;
                description: string;
                restTime: number;
                sets: {
                    weight: number;
                    repeatCount: number;
                    done: boolean;
                }[];
                muscleGroups: string[];
                useCustomSets: boolean;
            }[];
        };
        /** ActiveTrainingStartBody */
        ActiveTrainingStartBody: {
            id: string;
            dateStart: string;
        };
        /** UpdateActiveTrainingBody */
        UpdateActiveTrainingBody: {
            dateStart: string;
            name: string;
            description: string;
            exercises: {
                name: string;
                description: string;
                restTime: number;
                sets: {
                    weight: number;
                    repeatCount: number;
                    done: boolean;
                }[];
                muscleGroups: string[];
                useCustomSets: boolean;
            }[];
        };
        /** TrainingHistory */
        TrainingHistory: {
            id: string;
            name: string;
            description: string;
            exercises: {
                name: string;
                description: string;
                restTime: number;
                sets: {
                    weight: number;
                    repeatCount: number;
                    done: boolean;
                }[];
                muscleGroups: string[];
                useCustomSets: boolean;
            }[];
            dateStart: string;
        };
        /** TrainingHistoryUpdate */
        TrainingHistoryUpdate: {
            id: string;
            name: string;
            description: string;
            exercises: {
                name: string;
                description: string;
                restTime: number;
                sets: {
                    weight: number;
                    repeatCount: number;
                    done: boolean;
                }[];
                muscleGroups: string[];
                useCustomSets: boolean;
            }[];
            dateStart: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
