openapi: 3.0.0
info:
  title: Gym Application API
  description: API for gym and exercises management
  version: 1.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /auth/login:
    post:
      $ref: "./endpoints/auth.yaml#/login"

  /auth/register:
    post:
      $ref: "./endpoints/auth.yaml#/register"

  /auth/refresh:
    post:
      $ref: "./endpoints/auth.yaml#/refresh"

  /exercises:
    get:
      $ref: "./endpoints/exercises.yaml#/getAllExercises"
    post:
      $ref: "./endpoints/exercises.yaml#/createExercise"

  /exercises/{exerciseId}:
    get:
      $ref: "./endpoints/exercises.yaml#/getExerciseById"
    put:
      $ref: "./endpoints/exercises.yaml#/updateExercise"
    delete:
      $ref: "./endpoints/exercises.yaml#/deleteExercise"

  /trainings:
    get:
      $ref: "./endpoints/training.yaml#/getAllTrainings"
    post:
      $ref: "./endpoints/training.yaml#/createTraining"

  /trainings/{trainingId}:
    get:
      $ref: "./endpoints/training.yaml#/getTrainingById"
    put:
      $ref: "./endpoints/training.yaml#/updateTraining"
    delete:
      $ref: "./endpoints/training.yaml#/deleteTraining"

  # Активные тренировки (CRUD + операции)
  /active-trainings:
    get:
      $ref: "./endpoints/training-active.yaml#/getActiveTrainings"
    post:
      $ref: "./endpoints/training-active.yaml#/createActiveTraining"

  /active-trainings/{trainingId}:
    get:
      $ref: "./endpoints/training-active.yaml#/getActiveTrainingById"
    put:
      $ref: "./endpoints/training-active.yaml#/updateActiveTraining"
    delete:
      $ref: "./endpoints/training-active.yaml#/deleteActiveTraining"

  # Операции с тренировочным процессом
  /active-trainings/{trainingId}/start:
    post:
      $ref: "./endpoints/training-active.yaml#/startActiveTraining"

  # /active-trainings/{trainingId}/pause: - УДАЛЕНО (больше не используется)
  # /active-trainings/{trainingId}/resume: - УДАЛЕНО (больше не используется)

  /active-trainings/{trainingId}/complete:
    post:
      $ref: "./endpoints/training-active.yaml#/completeActiveTraining"

  /active-trainings/{trainingId}/cancel:
    post:
      $ref: "./endpoints/training-active.yaml#/cancelActiveTraining"

  # Управление упражнениями в активной тренировке - УДАЛЕНО (упражнение теперь встроено в тренировку)
  # /active-trainings/{trainingId}/exercises:
  # /active-trainings/{trainingId}/exercises/{exerciseId}:

  # История тренировок
  /training-history:
    get:
      $ref: "./endpoints/training-active.yaml#/getTrainingHistory"
